{
 "title": "DP Klausurtagung",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "dp_teams",
    "query": "http_server_requests_total{code=\"200\"}"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Panel Title", "type": "ryantxu-ajax-panel", "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 } },
  {
   "title": "$dp_teams (/metrics)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "repeat": "dp_teams",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_server_requests_total{instance=\"$dp_teams\", path=\"/metrics\"}",
     "legendFormat": "$dp_teams"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Pagerequests (metrics)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_total{path=\"/metrics\"}",
     "legendFormat": "${dp_teams}"
    }
   ]
  },
  {
   "title": "Pagerequests (root)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_total{path=\"/\"}",
     "legendFormat": "${dp_teams}"
    }
   ]
  }
 ]
}